config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  
  ActiveAdmin.routes(self)
  get 'examen_peliculas/index'
  get 'users/index'
  get 'settings/index'
  get 'statics/index'
  get 'statics/about'
  get 'comentarios/index'
  get 'movies/index'  
  get '/about' => 'statics#about', :as => :about

  # Resources
  resources :peliculas
  resources :comments
  resources :settings
  resources :charges

  root :to => "statics#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability
 
  def initialize(user)
      user ||= AdminUser.new # guest user (not logged in)
 
      if user.email == 'admin@email.com'
        can :manage, :all
      else
        can :read, Pelicula
       end
      # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/actor.rb
class Actor < ApplicationRecord
	# validates :name, :nationality, :year, presence:true
	# validates :name,  uniqueness: true
	# validates :nationality, format: { with: /\A[a-zA-Z 0-9]+\z/ }
	# validates :year, numericality: true, length: { maximum: 4 }
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	# validates :comment, presence:true, format: { with: /\A[a-zA-Z 0-9]+\z/ }
end

app/models/language.rb
class Language < ApplicationRecord
	# validates :language, uniqueness: true, length: { minimum: 2 }
	# validates :country, uniqueness: true, length: { minimum: 2 }
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
end

app/models/pelicula.rb
class Pelicula < ApplicationRecord
	# validates :name, :stars, :main_actor, :year, presence:true
	# validates :name, uniqueness: true
	# validates :stars, :numericality => {greater_than_or_equal_to:0, less_than_or_equal_to:5}
	# validates :main_actor, :name, format: { with: /\A[a-zA-Z 0-9]+\z/ }
	# validates :year, numericality: true, length: { maximum: 4 }
end

	def self.search(search)
  		where("actor like ?", "%" + "%#{search}%" + "%")
	end

app/models/setting.rb
class Setting < ApplicationRecord
  belongs_to :user
end

app/models/top_movie.rb
class TopMovie < ApplicationRecord
	# validates :name, :main_actor, :stars, presence:true
	# validates :name, uniqueness: true
	# validates :main_actor, :name, format: { with: /\A[a-zA-Z 0-9]+\z/ }
	# validates :stars, :numericality => {greater_than_or_equal_to:0, less_than_or_equal_to:5}
end

app/models/user.rb
class User < ApplicationRecord
	has_one :setting

	has_many :payments

	devise :database_authenticatable, :registerable,
    	    :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	
def new
end

def create
  # Amount in cents
  @amount = 500

  customer = Stripe::Customer.create(
    :email => params[:stripeEmail],
    :source  => params[:stripeToken]
  )

  charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => @amount,
    :description => 'Rails Stripe customer',
    :currency    => 'usd'
  )

rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to new_charge_path
end

end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :authenticate_user!
  layout "admin"
  
  def index
      @setting = current_user.setting
      # @payment = current_user.payments
      if params[:user][:email] == 'mi-email@email.com'
        @email = "mi email"
      else
        @email = "otro email"
      end

    end

    def new
      @setting = current_user.build_setting
  end


  def create
      @setting = current_user.build_setting(setting_params)
    if 
      @setting.save
      flash[:success] = t('setting.create_success')
      redirect_to settings_path
      else
      render :new
      end
  end
 
  def edit
      @setting = Setting.find(params[:id])
  end
 
  def update
   @setting = Setting.find(params[:id])
 
      if @setting.update_attributes(setting_params)
        flash[:success] = t('setting.create_success')
        redirect_to settings_path
        else
        render :index
        end
  end
 
 
private
  def setting_params
      params.require(:setting).permit(:country, :language)
  end  
 end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  skip_before_action :authenticate_user!
  def index
  	@peliculas = Pelicula.all
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def bootstrap_class_for(flash_type)
    case flash_type
    when "success"
      "alert-success"   # Green
    when "danger"
      "alert-danger"    # Red
    when "alert"
      "alert-warning"   # Yellow
    when "notice"
      "alert-info"      # Blue
    else
      flash_type.to_s
    end
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/peliculas_helper.rb
module PeliculasHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/settings/edit.html.erb
<div class="container">
	<%= form_for @setting do |setting|%>
 
	<%= setting.text_field :country%>
		<br>
	<%= setting.text_field :language%>
 
	<%= setting.submit "Change"%>
 
	<%end%>
</div>

app/views/settings/index.html.erb
<div class="container settingtxt"><!-- Start container -->
	<%= render "shared/header" %>

	<div class="row"><!-- Start row uno -->
		<div class="background1">
			<h6 class="rowunotxt">  </h6>
		</div>
	</div><!-- Finish row uno -->

	<div class="row" style="float:right;"><!-- Start row dos -->
		<button class="summarybtn">Summary</button>
		<button class="topbtn">Movie Ratings</button>
		<button class="topbtn">TV Ratings</button>
		<button class="topbtn">WTS/NI</button>
		<button class="topbtn">Quotes</button>
		<button class="topbtn">Lists</button>
		<button class="topbtn">My Critics</button>
	</div><!-- Finish row dos -->
		

	<div class="row"><!-- Start row tres -->
		<div class="col-lg-4 box4"><!-- Start col uno -->
			<img class="loginimg" src="https://msftmecprodstorage.blob.core.windows.net/images/EzMemberDefault.jpg"><br><br>
		  <h5 style="color:gray" class="imgtxt"><b>USER NAME HERE</b></h5><br>
      <h5 class="imgtxt" style="color: #0099ff">Manage Account <br><br>
      Profile Summary</h5><br>

       <!-- COMPROBACIO DE SETTING SI NO ES NULL -->     
      <%if !@setting.nil?%>
 
        <p><b>Country:</b>&nbsp;<%= @setting.country %></p>
        <p><b>Language:</b>&nbsp;<%= @setting.language %></p>
 
        <%= link_to 'Edit', edit_setting_path(@setting.id), :title => "Edit", class:'editbtn settingtxt', style:"color: white;" %>
        <br></br>  
      <%else%>
 
    <%= link_to 'Add', new_setting_path, title:"Add setting", class:"addbtn settingtxt", style:"color:white;" %>
 <%end%>


    </div><!-- Finish col uno -->

    <div class="col-lg-1"><!-- Start col dos --> 
    </div><!-- Finish col dos -->
      
		<div class="col-lg-7 box5"><!-- Start col tres -->
    <h4 class="box6"><b>WANT-TO-SEE MOVIES</b></h4>
      <img class="movie1" src="http://res.cloudinary.com/dy6weuz9h/image/upload/v1497435078/7_nry1mz.png">
      <img class="movie2" src="http://res.cloudinary.com/dy6weuz9h/image/upload/v1497435078/19_vlfbf1.png">
      <img class="movie3" src="http://res.cloudinary.com/dy6weuz9h/image/upload/v1497435077/10_ddkjcy.png">
      <img class="movie4" src="http://res.cloudinary.com/dy6weuz9h/image/upload/v1497435078/4_bjozfc.png">
		</div><!-- Finish col tres -->
	</div><!-- Finish row tres -->

  <div class="row"><!-- Start row cuatro -->
    <div class="col-lg-4 box5">
      <h4 class="box6"><b>PROFILE STATS</b></h4>
      <h5><b>Total Profile Views:</b><br>
          0 <br><br>
          <b>Profile Views Last 7 Days:</b><br>
          0</h5>
    </div><!-- Finish col cuatro -->
    
    <div class="col-lg-1"><!-- Start col cinco -->
    </div><!-- Finish col cinco -->
    
    <div class="col-lg-7 box5"><!-- Start col seis -->
      <h4 class="box6"><b>WANT-TO-SEE TV</b></h4>
      <img class="serie1" src="http://res.cloudinary.com/dy6weuz9h/image/upload/v1498474429/mediacover-18070-5_ujoctt.png"> 
      <img class="serie2" src="http://res.cloudinary.com/dy6weuz9h/image/upload/v1498474429/mediacover-7003-5_bmr6pt.png">
      <img class="serie3" src="http://res.cloudinary.com/dy6weuz9h/image/upload/v1498474430/mediacover-16820-5_osndy8.png">
      <img class="serie4" src="http://res.cloudinary.com/dy6weuz9h/image/upload/v1498475598/mediacover-18092-5_tx55vv.png">
    </div><!-- Finish col seis -->
  </div><!-- Finish row cuatro -->

  <div class="row"><!-- Start row cinco -->
    <div class="col-lg-4 box5"><!-- Start col siete -->
      <h4 class="box6"><b>ABOUT</b></h4>
      <h5><b>Member Since</b><br>
          0/00/0000</h5>
    </div><!-- Finish col siete -->

    <div class="col-lg-1"><!-- Start col ocho -->    
    </div><!-- Finish col ocho -->

    <div class="col-lg-7 box5"><!-- Start col nueve -->
      <h4 class="box6"><b>RATING HISTORY</b></h4><h5 style="float:right;">Movie Ratings  |  TV RatingsRATING HISTORY</h5>
      <h5>No recent ratings.</h5> <br><br>
      <h5 style="float:right;">Like my reviews? Nominate me as a Super Reviewer</h5>
    </div><!-- Finish col nueve -->
  </div><!-- Finish row cinco -->

<%if flash.present?%>
  <div class="row">
    <div class="col-sm-12 col-md-6 col-md-offset-3" style="padding:25px 0">
      <%= render partial: "shared/flash_messages", flash: flash %>
    </div>
  </div>
<%end%>

  <%= render "shared/footer" %>
</div><!-- Finish container -->

app/views/settings/new.html.erb
 <%= form_for(@setting) do |f| %>
    <%if flash.present?%>
<div class="row">
    <div class="col-sm-12 col-md-6 col-md-offset-3" style="padding:25px 0">
        <%= render partial: "shared/flash_messages", flash: flash %>
    </div>
</div>
<%end%>
    
    <div class="field">
        <%= f.text_field :country, placeholder: "Country", class:"form-control" %>
    </div>
    <div class="field">
        <%= f.text_field :language, placeholder: "Language", class:"form-control" %>
    </div>    
    	 
    <div class="field">
        <%= f.submit "Save", class:"btn btn-sm btn-danger white pull-right", style:"margin-top: 15px;" %>
    </div>
<% end %>