config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  
  ActiveAdmin.routes(self)
  get 'examen_peliculas/index'
  get 'users/index'
  get 'settings/index'
  get 'statics/index'
  get 'statics/about'
  get 'comentarios/index'
  get 'movies/index'  
  get '/about' => 'statics#about', :as => :about

  # Resources
  resources :peliculas
  resources :comments
  resources :settings
  resources :charges

  root :to => "statics#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability
 
  def initialize(user)
      user ||= AdminUser.new # guest user (not logged in)
 
      if user.email == 'admin@email.com'
        can :manage, :all
      else
        can :read, Pelicula
       end
      # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/actor.rb
class Actor < ApplicationRecord
	# validates :name, :nationality, :year, presence:true
	# validates :name,  uniqueness: true
	# validates :nationality, format: { with: /\A[a-zA-Z 0-9]+\z/ }
	# validates :year, numericality: true, length: { maximum: 4 }
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	# validates :comment, presence:true, format: { with: /\A[a-zA-Z 0-9]+\z/ }
end

app/models/language.rb
class Language < ApplicationRecord
	# validates :language, uniqueness: true, length: { minimum: 2 }
	# validates :country, uniqueness: true, length: { minimum: 2 }
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
end

app/models/pelicula.rb
class Pelicula < ApplicationRecord
	# validates :name, :stars, :main_actor, :year, presence:true
	# validates :name, uniqueness: true
	# validates :stars, :numericality => {greater_than_or_equal_to:0, less_than_or_equal_to:5}
	# validates :main_actor, :name, format: { with: /\A[a-zA-Z 0-9]+\z/ }
	# validates :year, numericality: true, length: { maximum: 4 }
end

	def self.search(search)
  		where("actor like ?", "%" + "%#{search}%" + "%")
	end

app/models/setting.rb
class Setting < ApplicationRecord
  belongs_to :user
end

app/models/top_movie.rb
class TopMovie < ApplicationRecord
	# validates :name, :main_actor, :stars, presence:true
	# validates :name, uniqueness: true
	# validates :main_actor, :name, format: { with: /\A[a-zA-Z 0-9]+\z/ }
	# validates :stars, :numericality => {greater_than_or_equal_to:0, less_than_or_equal_to:5}
end

app/models/user.rb
class User < ApplicationRecord
	has_one :setting

	has_many :payments

	devise :database_authenticatable, :registerable,
    	    :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	
def new
end

def create
  # Amount in cents
  @amount = 500

  customer = Stripe::Customer.create(
    :email => params[:stripeEmail],
    :source  => params[:stripeToken]
  )

  charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => @amount,
    :description => 'Rails Stripe customer',
    :currency    => 'usd'
  )

rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to new_charge_path
end

end

app/controllers/peliculas_controller.rb
class PeliculasController < ApplicationController

	def index  
		#Muestra las películas que hay en la base de datos.
		@peliculas = Pelicula.all
	end
   
	def show
		@pelicula = Pelicula.find(params[:id])
	end
   
	def new
		@pelicula = Pelicula.new
	end
   
	def create
		@pelicula = Pelicula.new(peli_params)

		if @pelicula.save
			redirect_to peliculas_path, :notice => "Se ha guardado la pelicula"
		else
		render "new"
		end
	end
   
	def edit
		@pelicula = Pelicula.find(params[:id])	
	end
   
	def update
		@pelicula = Pelicula.find(params[:id])
 
		if @pelicula.update_attributes(peli_params)
			redirect_to peliculas_path, :notice => "éxito!" 
		else
			render "edit"
		end 
	end
   
	def destroy
		@pelicula = Pelicula.find(params[:id])
		@pelicula.destroy
		redirect_to peliculas_path, :notice => "Borrado"
    end
  

	private 
		def peli_params
			params.require(:pelicula).permit(:name, :main_actor, :stars, :year, :url, :director)
		end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  skip_before_action :authenticate_user!
  def index
  	@peliculas = Pelicula.all
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def bootstrap_class_for(flash_type)
    case flash_type
    when "success"
      "alert-success"   # Green
    when "danger"
      "alert-danger"    # Red
    when "alert"
      "alert-warning"   # Yellow
    when "notice"
      "alert-info"      # Blue
    else
      flash_type.to_s
    end
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/peliculas_helper.rb
module PeliculasHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/peliculas/edit.html.erb
<div class="container">
	<%= form_for @pelicula do |peli|%>
 
	<%= peli.text_field :name%>
		<br>
	<%= peli.text_field :stars%>
		<br>
	<%= peli.text_field :main_actor%>
		<br>
	<%= peli.text_field :year%>
	
 
	<%= peli.submit "Enviar Pelicula "%>
 
	<%end%>
</div>

app/views/peliculas/index.html.erb
<div class="container">

<h1>Aquí todas las películas que tenemos en la BBDD</h1>

<% @peliculas.each do |peli| %>

	<p><%= link_to peli.name, peli %></p>
	<p><%= peli.stars %></p>
	<p><%= peli.main_actor %></p>
	<p><%= peli.year %></p>

<p><%= link_to "Editar Pelicula", edit_pelicula_path(peli) %></p>


<% end %>

<p><%= link_to "Añadir nueva Pelicula", new_pelicula_path%></p>

</div>

app/views/peliculas/new.html.erb
<div class="container">
<h2>Añade aqui una nueva pelicula</h2>

	<%= form_for @pelicula do |peli| %>

	<p>
		<%= peli.label :name %> <br/>
		<%= peli.text_field :name %>
	</p>

	<p>
		<%= peli.label :stars %> <br/>
		<%= peli.text_field :stars %>
	</p>

	<p>
		<%= peli.label :main_actor %> <br/>
		<%= peli.text_field :main_actor %>
	</p>

	<p>
		<%= peli.label :year %> <br/>
		<%= peli.text_field :year %>
	</p>

		<%= peli.submit "Añadir Pelicula"%>

	<% end %>

	<p> <%= link_to "Añadir nueva Pelicula", new_pelicula_path %> </p>
</div>

app/views/peliculas/show.html.erb
<div class="container">
	<b>Nombre de la película:</b> <%= @pelicula.name %>
		<br>
	<b>Estrellas que tiene:</b> <%= @pelicula.stars %>
		<br>
	<b>Actor Principal:</b> <%= @pelicula.main_actor %>
		<br>
	<b>Año:</b> <%= @pelicula.year %>
		<br>
	<b>Se anadió a la base de datos el...</b> <%= @pelicula.created_at %>


	<%= link_to "Delete", pelicula_path(@pelicula),
							:method => :delete %>
</div>