config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  
  ActiveAdmin.routes(self)
  get 'examen_peliculas/index'
  get 'users/index'
  get 'settings/index'
  get 'statics/index'
  get 'statics/about'
  get 'comentarios/index'
  get 'movies/index'  
  get '/about' => 'statics#about', :as => :about

  # Resources
  resources :peliculas
  resources :comments
  resources :settings
  resources :charges

  root :to => "statics#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability
 
  def initialize(user)
      user ||= AdminUser.new # guest user (not logged in)
 
      if user.email == 'admin@email.com'
        can :manage, :all
      else
        can :read, Pelicula
       end
      # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/actor.rb
class Actor < ApplicationRecord
	# validates :name, :nationality, :year, presence:true
	# validates :name,  uniqueness: true
	# validates :nationality, format: { with: /\A[a-zA-Z 0-9]+\z/ }
	# validates :year, numericality: true, length: { maximum: 4 }
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	# validates :comment, presence:true, format: { with: /\A[a-zA-Z 0-9]+\z/ }
end

app/models/language.rb
class Language < ApplicationRecord
	# validates :language, uniqueness: true, length: { minimum: 2 }
	# validates :country, uniqueness: true, length: { minimum: 2 }
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
end

app/models/pelicula.rb
class Pelicula < ApplicationRecord
	# validates :name, :stars, :main_actor, :year, presence:true
	# validates :name, uniqueness: true
	# validates :stars, :numericality => {greater_than_or_equal_to:0, less_than_or_equal_to:5}
	# validates :main_actor, :name, format: { with: /\A[a-zA-Z 0-9]+\z/ }
	# validates :year, numericality: true, length: { maximum: 4 }
end

	def self.search(search)
  		where("actor like ?", "%" + "%#{search}%" + "%")
	end

app/models/setting.rb
class Setting < ApplicationRecord
  belongs_to :user
end

app/models/top_movie.rb
class TopMovie < ApplicationRecord
	# validates :name, :main_actor, :stars, presence:true
	# validates :name, uniqueness: true
	# validates :main_actor, :name, format: { with: /\A[a-zA-Z 0-9]+\z/ }
	# validates :stars, :numericality => {greater_than_or_equal_to:0, less_than_or_equal_to:5}
end

app/models/user.rb
class User < ApplicationRecord
	has_one :setting

	has_many :payments

	devise :database_authenticatable, :registerable,
    	    :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	
def new
end

def create
  # Amount in cents
  @amount = 500

  customer = Stripe::Customer.create(
    :email => params[:stripeEmail],
    :source  => params[:stripeToken]
  )

  charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => @amount,
    :description => 'Rails Stripe customer',
    :currency    => 'usd'
  )

rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to new_charge_path
end

end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  skip_before_action :authenticate_user!
  def index
  	@peliculas = Pelicula.all
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def bootstrap_class_for(flash_type)
    case flash_type
    when "success"
      "alert-success"   # Green
    when "danger"
      "alert-danger"    # Red
    when "alert"
      "alert-warning"   # Yellow
    when "notice"
      "alert-info"      # Blue
    else
      flash_type.to_s
    end
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/comentarios_helper.rb
module ComentariosHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/peliculas_helper.rb
module PeliculasHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/charges/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"
          data-locale="auto"></script>
<% end %>

app/views/charges/views.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/statics/about.html.erb
<div class="container allbackground"><!-- Start container -->
	<%= render "shared/header" %>
		<div class="row"><!-- Start row uno -->
			<div class="background1">
				<h6 class="rowunotxt">TRENDING ON RT</h6>
			</div>
		</div><!-- Finish row uno -->

		<div class="row">
			<div class="col-lg-8">
				<h3><b>ABOUT KUKI TOMATOES®</b></h3>
				<p>Kuki Tomatoes® and the Tomatometer® rating is the most trusted measurement of quality entertainment. As the leading online aggregator of movie and TV show reviews from professional critics, Rotten Tomatoes offers the most comprehensive guide to what's fresh. The world famous Tomatometer rating represents the percentage of positive professional reviews for films and TV shows and is used by millions every day, to help with their entertainment viewing decisions. Rotten Tomatoes designates the best reviewed movies and TV shows as Certified Fresh™. That accolade is awarded with Tomatometer ratings of 75% and higher, and a required minimum number of reviews. Weekly Rotten Tomatoes podcasts can be found on RottenTomatoes.com, iTunes, Soundcloud and Stitcher, and Rotten Tomatoes' entertainment experts make regular TV and radio appearances across the US. In 2016, Flixster and Rotten Tomatoes became part of Fandango's portfolio of digital properties, serving moviegoers and entertainment fans.</p>
				 <br><br>
				<h4><b>WHAT IS THE TOMATOMETER®?</b></h4>
				<p>The Tomatometer rating - based on the published opinions of hundreds of film and television critics - is a trusted measurement of movie and TV programming quality for millions of moviegoers.

				The Tomatometer rating represents the percentage of professional critic reviews that are positive for a given film or television show.

				Back in the days of the open theaters, when a play was particularly atrocious, the audience expressed their dissatisfaction by not only booing and hissing at the stage, but throwing whatever was at hand -- vegetables and fruits included.</p>
			</div>
			
			<div class="col-lg-4">
					<br>
				<button class="contactbtn"><b>CONTACT US</b></button>
					<br><br>
				<p><b>Customer Support</b>
					<br>
				Visit our FAQs or fill out our Email Form.
					<br><br>
				<b>Licensing or Partnership Inquiries</b>
					<br>
				Fill out our Business Proposal Form.
					<br><br>
				<b>Submit Movie Information</b>
					<br>
				Tell us about missing or incorrect movie or TV information.
					<br><br>
				<b>Advertise</b>
					<br>
				Review Fandango Advertising Opportunities.</p>	
			</div>
		</div>
<%= render "shared/footer" %>
</div><!-- Finish container -->

app/views/statics/index.html.erb
<%= render "shared/header" %>
<!--  -->
<div class="container alltxt"><!-- Start container -->
		<div class="row"><!-- Start row uno -->
			<div class="background1">
				<h6 class="rowunotxt">TRENDING ON RT</h6>
			</div>
		</div><!-- Finish row uno -->

    <!-- Start boxes -->
		<div class="row"><!-- Start row dos -->
      <div class="col-lg-6 box1"><!-- Star col uno -->
        <img class="imagehvr img2" src="http://res.cloudinary.com/dy6weuz9h/image/upload/v1496303561/c5_sxcewn.png">
  		</div><!-- Finish col uno -->

			<div class="col-lg-3 box2"><!-- Start col dos -->
				<img class="imagehvr img3" src="http://res.cloudinary.com/dy6weuz9h/image/upload/v1496303561/ww_rxlcwk.png">
			</div><!-- Finish col dos -->

			<div class="col-lg-3 box3"><!-- Start col tres -->	
				<img class="imagehvr img4" src="http://res.cloudinary.com/dy6weuz9h/image/upload/v1496233388/Sin_t%C3%ADtulo_2_kd36lh.png">
			</div><!-- Finish col tres -->
		</div><!-- Finish row dos -->
    <!-- Finsih boxes -->

    <!-- Start list -->
		<div class="row"><!-- Start row tres -->
			<div class="col-lg-6 boxtabla1"><!-- Start col siete -->
				<h4><b>MOVIES OPENING THIS WEEK</b></h4>

		    <!-- Start tabla pelis -->
				<table class="table table-hover table-striped" border="0">	
				<tbody>
					<h4><tr class="alltxt">
					  <th>STARS</th>	
					  <th>MOVIE NAME</th>
					  <th>ACTOR</th>
					  <th>YEAR</th>
					  <th>ID</th>
					</tr></h4>		
				</tbody>

				<% @peliculas.each do |peli| %>
					<tr>
						<td style="background-color: white;" class="alltxt2">
							<span class="fa fa-star">&nbsp;</span><%= peli.stars %>
						</td>
				
						<td style="background-color: white;" class="alltxt2"> 
							<%= link_to peli.name, pelicula_path(peli), :title => "Visualizar" %> 
						</td>
				 
						<td style="background-color: white;" class="alltxt2">
							<%= peli.main_actor %>
						</td>
				 
						<td style="background-color: white;" class="alltxt2">
							<%= peli.year %>	
						</td>
				 
						<td style="background-color: white;" class="alltxt2">
							<%= peli.id  %> 
						</td> 
					</tr>
				<% end %>
				</table>
		    <!-- Finish tabla peliculas -->				                


				<h4><b>TOP BOX OFFICE</b></h4>
				<table class="table">
  					<tr>
    					<th><img class="miniimg" src="http://coopecanera.com/wp-content/uploads/2014/11/mancha-verde.png">  31%</th>
    					<th>Pirates of the Caribbean: Dead men tell no tiles</th>
    					<th>  </th>
  					</tr>
  					<tr>
    					<th><img class="miniimg" src="http://res.cloudinary.com/dy6weuz9h/image/upload/v1496231557/1_burned_fepmac.png">  81%</th>
    					<th>Guardians of the Galaxy VOL.2</th>
    					<th>  </th>
  					</tr>
  					<tr>
    					<th><img class="miniimg" src="http://coopecanera.com/wp-content/uploads/2014/11/mancha-verde.png">  19%</th>
    					<th>Baywatch</th>
    					<th>  </th>
  					</tr>
  					<tr>
    					<th><img class="miniimg" src="http://res.cloudinary.com/dy6weuz9h/image/upload/v1496231557/1_burned_fepmac.png">  71%</th>
    					<th>Alien: Covenant</th>
    					<th>  </th>
  					</tr>
  					<tr>
    					<th><img class="miniimg" src="http://coopecanera.com/wp-content/uploads/2014/11/mancha-verde.png">  46%</th>
    					<th>Everything, Everything</th>
    					<th>  </th>
  					</tr>
  					<tr>
    					<th><img class="miniimg" src="http://coopecanera.com/wp-content/uploads/2014/11/mancha-verde.png">  17%</th>
    					<th>Diary Of A Wimpy Kid: The Long Haul</th>
    					<th>  </th>
  					</tr>
  					<tr>
    					<th><img class="miniimg" src="http://res.cloudinary.com/dy6weuz9h/image/upload/v1496231557/1_burned_fepmac.png">  37%</th>
    					<th>Snatched</th>
    					<th>  </th>
  					</tr>
  					<tr>
    					<th><img class="miniimg" src="http://coopecanera.com/wp-content/uploads/2014/11/mancha-verde.png">  28%</th>
    					<th>King Arthur: Legend of the Sword</th>
    					<th>  </th>
  					</tr>
  					<tr>
    					<th><img class="miniimg" src="http://coopecanera.com/wp-content/uploads/2014/11/mancha-verde.png">  52%</th>
    					<th>The Boss Baby</th>
    					<th>  </th>
  					</tr>
  					<tr>
    					<th><img class="miniimg" src="http://res.cloudinary.com/dy6weuz9h/image/upload/v1496231557/1_burned_fepmac.png">  71%</th>
    					<th>Beauty and the Beast</th>
    					<th>  </th>
  					</tr>
				</table>

				</div><!-- Finish col siete -->

			<div class="col-lg-6 boxtabla2"><!-- Start col ocho -->
				<h4><b>NEW TV TONIGHT</b></h4>
				<table class="table">
  					<tr>
    					<th><img class="miniimg" src="http://images.gofreedownload.net/tomato-238102.jpg">  90%</th>
    					<th>Downward Dog: Season 1</th>
    					<th>  </th>
  					</tr>
  					<tr>
    					<th><img class="miniimg" src="http://images.gofreedownload.net/tomato-238102.jpg">  100%</th>
    					<th>House of Cards: Season 5</th>
    					<th>  </th>
  					</tr>
  					<tr>
    					<th><img class="miniimg" src="http://images.gofreedownload.net/tomato-238102.jpg">  100%</th>
    					<th>iZombie: Season 3</th>
    					<th>  </th>
  					</tr>
  					<tr>
    					<th><img class="miniimg" src="http://images.gofreedownload.net/tomato-238102.jpg">  97%</th>
    					<th>The Americans: Season 5</th>
    					<th>  </th>
  					</tr>
  					<tr>
    					<th><img class="miniimg" src="http://res.cloudinary.com/dy6weuz9h/image/upload/v1496231557/1_burned_fepmac.png">  83%</th>
    					<th>Genius: Season 1</th>
    					<th>  </th>
  					</tr>
  					<tr>
    					<th><img class="miniimg" src="http://res.cloudinary.com/dy6weuz9h/image/upload/v1496231557/1_burned_fepmac.png">  78%</th>
    					<th>Victorian Slum House: Season 1</th>
    					<th>  </th>
  					</tr>
  					<tr>
    					<th><img class="miniimg" src="http://coopecanera.com/wp-content/uploads/2014/11/mancha-verde.png">  55%</th>
    					<th>Prision Break: Season 5</th>
    					<th>  </th>
  					</tr>
  					<tr>
    					<th><img class="miniimg" src="http://coopecanera.com/wp-content/uploads/2014/11/mancha-verde.png">  25%</th>
    					<th>Imaginary Mary: Season 1</th>
    					<th>  </th>
  					</tr>
  					<tr>
    					<th><h6>Not  Score Yet</h6></th>
    					<th>Casual: Season 3</th>
    					<th>  </th>
  					</tr>
  					<tr>
    					<th><h6>Not  Score Yet</h6></th>
    					<th>Famous in Love: Season 1</th>
    					<th>  </th>
  					</tr>
  					<tr>
    					<th><h6>Not  Score Yet</h6></th>
    					<th>American Epic: Season 1</th>
    					<th>  </th>
  					</tr>
				</table>			

				<h4><b>MOST POPULAR TV ON RT</b></h4>
				<table class="table">
  					<tr>
    					<th><img class="miniimg" src="http://images.gofreedownload.net/tomato-238102.jpg"> 95%</th>
    					<th>Twin Peaks: The Return</th>
    					<th>  </th>
  					</tr>
  					<tr>
    					<th><img class="miniimg" src="http://images.gofreedownload.net/tomato-238102.jpg">96%</th>
    					<th>American Gods: Season 1</th>
    					<th>  </th>
  					</tr>
  					<tr>
    					<th><img class="miniimg" src="http://images.gofreedownload.net/tomato-238102.jpg">100%</th>
    					<th>Master of None: Season 2</th>
    					<th>  </th>
  					</tr>
  					<tr>
    					<th><img class="miniimg" src="http://images.gofreedownload.net/tomato-238102.jpg">100%</th>
    					<th>The Handmaid's Tale: Season 1</th>
    					<th>  </th>
  					</tr>
  					<tr>
    					<th><img class="miniimg" src="http://images.gofreedownload.net/tomato-238102.jpg">98%</th>
    					<th>The Leftovers: Season 3</th>
    					<th>  </th>
  					</tr>
  					<tr>
    					<th><img class="miniimg" src="http://images.gofreedownload.net/tomato-238102.jpg">93%</th>
    					<th>The Keepers: Miniseries</th>
    					<th>  </th>
  					</tr>
				</table>

				<h4><b>TOP DVD & STREAMING MOVIES</b></h4>
				<h6>FandangoNOW | Nerflix | iTunes | Amazon | More...</h6>
				<table class="table">
  					<tr>
    					<th><img class="miniimg" src="http://images.gofreedownload.net/tomato-238102.jpg">  92%</th>
    					<th>Logan</th>
    					<th>  </th>
  					</tr>
  					<tr>
    					<th><img class="miniimg" src="http://images.gofreedownload.net/tomato-238102.jpg">  99%</th>
    					<th>Get Out</th>
    					<th>  </th>
  					</tr>
  					<tr>
    					<th><img class="miniimg" src="http://coopecanera.com/wp-content/uploads/2014/11/mancha-verde.png">  35%</th>
    					<th>The Great Wall/th>
    					<th>  </th>
  					</tr>
  					<tr>
    					<th><img class="miniimg" src="http://res.cloudinary.com/dy6weuz9h/image/upload/v1496231557/1_burned_fepmac.png">  76%</th>
    					<th>Wakefield/th>
    					<th>  </th>
  					</tr>
  					<tr>
    					<th><img class="miniimg" src="http://images.gofreedownload.net/tomato-238102.jpg">  100%</th>
    					<th>My Life as Zucchini (Ma Vie de Courgette)</th>
    					<th>  </th>
  					</tr>
				</table>	
			</div><!-- Finish col ocho -->
		</div><!-- Finish row tres -->
    <!-- Finish list -->

    <div class="row"><h4><b>MOVIE TRAILERS</b></h4></div>
    <div class="row"><!-- Start row cuatro -->
      <div class="col-lg-4"><!-- Start col nueve -->
        <h4>IT</h4>
        <iframe width="100%" height="250px" src="https://www.youtube.com/embed/FnCdOQsX5kc" frameborder="0" allowfullscreen></iframe>
      </div><!-- Finish col nueve -->

      <div class="col-lg-4"><!-- Start col diez -->
        <h4>Wonder Woman</h4> 
        <iframe width="100%" height="250px" src="https://www.youtube.com/embed/VSB4wGIdDwo" frameborder="0" allowfullscreen></iframe>
      </div><!-- Finish col diez -->

      <div class="col-lg-4"><!-- Start col once -->
        <h4>Thor: Ragnarok</h4> 
        <iframe width="100%" height="250px" src="https://www.youtube.com/embed/v7MGUNV8MxU" frameborder="0" allowfullscreen></iframe>
      </div><!-- Finish col once -->
    </div><!-- Finish row cuatro -->

<!-- ****************************** -->
    <br><br><br><br>
    <div class="row"><!-- Start row cinco -->
      <div class="col-sm-12" style="text-align:center;"><!-- Start col doce -->
        <%= form_tag(root_path, :method => "get", id: "search-form") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Search Posts" %>
        <%= submit_tag t('general.send') %>
        <% end %>
      </div><!-- Finish col doce -->
    </div><!-- Finish row cinco -->
<br><br>
    <div class="row"><!-- Start row seis -->
    <%@peliculas.each do |peli|%>
    <div class="col-sm-6 col-md-4 col-lg-3"><!-- Start col trece -->
        <div class="latest-movie">
            <a href="#"><img src="<%=peli.url%>"></a>
            <p><b>Nombre:</b> <%=peli.name%></p>
            <p><b>Director:</b> <%=peli.director%></p>
            <p><b>Año:</b> <%=peli.year%></p>
        </div><!-- Finish col trece -->
    </div><!-- Finish row seis -->
    <%end%>
</div>
<!-- ****************************** -->

<%= render "shared/footer" %>
    
</div><!-- Finish container -->